# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nepp_Students' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenCV', '~> 3.3.1'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # Pods for Nepp_Students

end
